### ISSUE TITLE
Generate bindings for latest pytorch release

### ISSUE THREAD

**Issue by bytesnake** [LaurentMazare/tch-rs#136]
There is an awesome PR for pytorch, which speeds up the forward, as well as, backpropagation step in word embeddings significantly (https://github.com/pytorch/pytorch/issues/31356)

As they created the patches for the latest pytorch version, I want to update the bindings in a local copy. Is there any guide how to do this or could you give me some advice? According to the README the bindings are coming from `ocaml-torch`, but I'm not sure how to generate it.

**Comment by LaurentMazare** [comment]
Here is how you could generate the bindings:
- Copy the `Declarations.yaml` file generated during the compilation of your pytorch version in the `tch-rs/data/` directory.
- Install an ocaml toolchain, the best is probably to go via [opam](https://opam.ocaml.org/) and install `dune` and the other dependencies via `opam install ...`.
- Run `make gen` in your `tch-rs` directory, this will generate some C and rust files.

However it's possible for it not to work out of the box because of PyTorch changes. It has been almost 3 months since the release of PyTorch 1.3 so I would expect the amount of changes to be on the large side. PyTorch 1.4 is probably likely to be released soon, at this point I'll update the repo for this so it may be easier to generate bindings for a custom version just after this happens.

Anyway let me know if I can be of any help.

**Comment by bytesnake** [comment]
Thanks again

**Comment by LaurentMazare** [comment]
Ah sorry I should have told you that I just pushed some updates for PyTorch 1.4 which hopefully should make generating bindings for the github tip a bit easier. Let me know if you give it a try and need some help.

**Comment by bytesnake** [comment]
I modified the patches against the older version, which was less effort than updating the bindings :sweat_smile: but I'm looking forward into the new release, unfortunately my time is limited and I will just stick with my running version. But keep up the good work!
