### ISSUE TITLE
Deprecation of Failure crate

### ISSUE THREAD

**Issue by guillaume-be** [LaurentMazare/tch-rs#186]
Hello,

It has been raised to my attention via the following [issue](https://github.com/guillaume-be/rust-bert/issues/30) that the Failure crate is being deprecated.

I see `tch-rs` still relies on it, but these use could be easily replaced by using the `Result<_, Err>` return type instead of `Faillible`. Would you be interested in support in making these changes in the library, or would you like to continue relying on it for the time being?

**Comment by LaurentMazare** [comment]
Thanks for bringing this up, I just created a PR to switch from the `failure` crate to `anyhow` #187 (which is recommended on the `failure` crate readme).
It's a large change, although very mechanical, so probably worth thinking a bit more about it before merging.
Would you be happy with `anyhow`?

**Comment by danieldk** [comment]
Would it be possible to return a concrete error type? As far as I understand, `anyhow` is more for applications that do not care about concrete error types than library crates. Of course, `anyhow` would still be an improvement over the deprecated `failure` crate, since it's directly built on `Error` from the standard library.

**Comment by danieldk** [comment]
Forgot to add, the `thiserror` crate from the same author as `anyhow` is nice for implementing library-specific errors.

I can try to do a PR.

**Comment by danieldk** [comment]
Proposed draft PR: #189

**Comment by LaurentMazare** [comment]
Closing this issue now that the PR has been released!
