### ISSUE TITLE
`tch::vision::image::save` does not work as expected

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#195]
I stumbled across this issue while working on #194. This is a minimal [gist](https://gist.github.com/jerry73204/fce961f87238d630c465a295e02d9f63) to create a purely red image in tensor and call `tch::vision::image::save` to create an image. The resulting image has blue strides which is not expected, as shown in the link https://imgur.com/zCLPW76. It is broken on all tensor variants (f32, i32, i64, max = 1 or 255).

**Comment by LaurentMazare** [comment]
Actually the input tensor type was supposed to be UInt8 rather than Float which explains the weird artifacts that you saw. I've made it clearer in the documentation + added some conversion just in case. Note that you should use values that range from 0 to 255, using your example tensor * 255 you should see a purely red image.

**Comment by LaurentMazare** [comment]
Closing this for now as the documentation hopefully reflects properly how this is to be used.
