### ISSUE TITLE
Is tch-rs is can be implemented with wasm

### ISSUE THREAD

**Issue by amiyamandal-dev** [LaurentMazare/tch-rs#256]
I have an idea to implement wasm and tch-rs so the app can leverage real-time machine learning models.
But build failed cause wasm uses wasm32-unknown-unknown toolchain whereas nightly-x86_64-unknown-linux-gnu for any project for tch-rs.
It's possible to do so with this crate.

**Comment by tiberiusferreira** [comment]
This crate depends on Pytorch itself and links to it during build time, so you would need the Pytorch C++ lib itself to compile to WASM. 
Also, note that Pytorch tries to use Intel's library Math Kernel Library and Nvidia libraries for performance reasons, it would not be possible to compile these libs to Webassembly since they are very hardware specific.

**Comment by amiyamandal-dev** [comment]
@tiberiusferreira thanks, seem a bit impossible collaboration. So is there any way to do the integration

**Comment by tiberiusferreira** [comment]
Hello @amiyamandal-dev sorry for the delay. Yeah, it is theoretically possible to compile tch-rs + Pytorch C++ to wasm, but it would require compiling the CPU only non-vendor specific parts.  I expect something like: https://webmachinelearning.github.io/webnn/ to make it easier to run Deep Learning in the browser.

**Comment by amiyamandal-dev** [comment]
webnn seem pretty neat and I guess that the future and thanks for the reply.
