### ISSUE TITLE
Why using internal_cudnn_rnn_flatten_weight for LSTM but not GRU?

### ISSUE THREAD

**Issue by TLecailtel** [LaurentMazare/tch-rs#301]
Hello,

I noticed that your LSTM implementation uses `Tensor::internal_cudnn_rnn_flatten_weight`.
https://github.com/LaurentMazare/tch-rs/blob/ae79df5858535bc27eab38a09d3de4ee54d12dcf/src/nn/rnn.rs#L106-L116

But the GRU doesn't.
Is there a reason for that?

Also, the flattening is only performed at the creation of the LSTM layer.
Would it be possible to create a [flatten_parameters](https://pytorch.org/docs/stable/generated/torch.nn.RNNBase.html?highlight=flatten_parameters#torch.nn.RNNBase.flatten_parameters) method for the RNNs, like the one in Pytorch?

(I'm currently porting the [CharBERT](https://github.com/wtma/CharBERT) Python model to Rust, and their implementation flattens the weights of a GRU layer at each forward pass, as seen [here](https://github.com/wtma/CharBERT/blob/0ac763bf077fbc672cfe70c4aa40454857d93963/modeling/modeling_charbert.py#L42).)

Thank you!

**Comment by LaurentMazare** [comment]
I don't think there is a good reason for this not to be done on GRUs too. Theses RNNs used to work without flattening on early versions of the libtorch library, then this was required so the LSTM was tweaked because we noticed the issue while running some models but probably nobody noticed for GRU (sadly our CI tests are not run on gpus at the moment).
Anyway we should probably fix this, feel free to make a PR for this if you want otherwise I'll make the tweak in the next few days.

Re the `flatten_parameters` I don't have a strong feeling about it but I don't really see why you would want to re-flatten things after each forward pass, maybe you have some specific scenarios where this is useful?

**Comment by LaurentMazare** [comment]
I just pushed some changes to flatten the parameters when creating a GRU layer, let me know if you run into any further issues.

**Comment by TLecailtel** [comment]
Thanks for the quick reply and fix.

About `flatten_parameters`, [this](https://discuss.pytorch.org/t/why-do-we-need-flatten-parameters-when-using-rnn-with-dataparallel/46506/3) and [this](https://discuss.pytorch.org/t/rnn-module-weights-are-not-part-of-single-contiguous-chunk-of-memory/6011/14) show that flattening params in each forward pass of the RNN could prevent a memory error (or at least a warning) from happening.

But I haven't run into this problem myself, so I can't tell whether this solution is overkill or not.

**Comment by LaurentMazare** [comment]
I haven't read these threads fully but at least one of the issues seems to be related to moving the module across device which one can do in the Python version but is not possible in this crate. So I would be in favour of waiting to see if this can actually cause some issue and add the necessary method if that's the case (I'm a bit cautious about adding new methods as retiring them is could result in breaking user's code).

**Comment by TLecailtel** [comment]
Sure! I'm closing the issue then, thanks again.
