### ISSUE TITLE
Provide add-with-scalar-multiply method

### ISSUE THREAD

**Issue by edlanglois** [LaurentMazare/tch-rs#350]
Unless I'm missing something, `tch` does not include the full `x + alpha * y` interface for `add` and `add_` that exists in the C++ API:
https://pytorch.org/cppdocs/api/classat_1_1_tensor.html#_CPPv4NK2at6Tensor3addERKN2at6ScalarERKN2at6ScalarE

I have only been able to find `g_add` (add a tensor) and `g_add1` (add a scalar)
https://docs.rs/tch/0.4.1/tch/struct.Tensor.html#method.g_add

Could you add the version with both arguments?

**Comment by LaurentMazare** [comment]
That's actually not as straightforward as it looks: the bindings are automatically generated but rust does not have a very idiomatic way to handle argument with default values so we discard those and in this case it's actually an argument with a default value (`alpha` is 1 by default).
We could consider exposing this manually if you really care a lot about performance but maybe it's fine for you to make two separate function calls - also note that if you don't need to intercept errors you can use the arithmetic operators rather than `g_add` etc.

**Comment by edlanglois** [comment]
That makes sense. It's not a problem for me to use two function calls (or `addcmul`), I just figured I would try to use the most efficient approach if available.
