### ISSUE TITLE
LBFGS Support

### ISSUE THREAD

**Issue by joverwey** [LaurentMazare/tch-rs#368]
Is there a reason why LBFGS is not supported as an optimizer? Would it be hard to add?

For Style Transfer, I've noticed that it converges much faster than AdamW when used from Python.

Also see this comparison with other optimizers:
https://blog.slavv.com/picking-an-optimizer-for-style-transfer-86e7b8cba84b

**Comment by LaurentMazare** [comment]
`tch` is a thin layer around the C++ libtorch api. It seems that LBFGS is implemented mostly on the Python side for PyTorch (see the code [here](https://pytorch.org/docs/stable/_modules/torch/optim/lbfgs.html#LBFGS)) so that's a bit out of scope for `tch` and might be better suited for an external crate to implement.
Closing this issue as it has been a while but feel free to re-open if it's still a problem.
