### ISSUE TITLE
Take very long time to build torch-sys with CUDA

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#42]
I build the my package with tch dep and pass TORCH\_CUDA\_VERSION env. I observe that it stucks at compiling torch-sys for more than 10 minutes.

```sh
env TORCH_CUDA_VERSION=9.0 cargo build
```

I made a quick diagnosis by lsof and strace. The build script took very long time to unzip the [libtorch zip file](https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-latest.zip).  The I/O rate only peaks at 5 MiB/s. The build takes place on an SSD disk so disk I/O should not be bottleneck. In contrast, the command `unzip v1.1.0.zip` completes in seconds. May we consider replace the zip crate with [zip-sys](https://github.com/danielpclark/zip-sys), or faster implementations?

**Comment by LaurentMazare** [comment]
Thanks for reporting this.
First I would strongly recommend you to install torch manually and set the `LIBTORCH` environment variable. This is described in the main readme and will avoid having to download/unzip this file on each `cargo clean`.

Concerning the zip performance, my guess is that this is caused by the build script being compiled in debug mode. Hopefully this [rfc](https://github.com/rust-lang/rust/issues/48683) will let you compile the build script in release mode even when compiling overall in debug mode.
An easy thing that we could tweak now would be on linux platforms to first try running `unzip -d` fallback to the current behavior if this fails.

**Comment by jerry73204** [comment]
I missed that. Thanks. I think we could elaborate that LIBTORCH env indicates the install _prefix_ in README. I thought it was `/usr/include/torch` or some, but found be `/usr` when I read the source code.
Cargo profile dependencies works for me. Though it's available when rust nightly is default., it reduces time to handful minutes.
