### ISSUE TITLE
Memory allocation best practice

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#43]
Here is my scenario: I'm working on a huge custom data set. The iterator code loads images sequentially and convert to tensor by `Tensor::of_slice()`. However, I observed obvious memory growing and got OOM eventually.

The code can be as simple as:
```rust
for array in data_source {
    let tensor = Tensor::of_slice(array.as_slice()).to_device(gpu_device);
    let output = model.forward_t(&tensor);
}
```

Although I comment out my model code and leave `of_slice()` alone, the memory still grows even the tensor goes out of scope. Hence, I got some wondering:

* What's is _canonical_ way to feed custom data set?
*  When and which action triggers the deallocation of tensor? It is done automatically or manually?
* Does the second `forward_t()` double the memory?

**Comment by LaurentMazare** [comment]
Would you have a repro for this ?
I just pushed a [small example](https://github.com/LaurentMazare/tch-rs/blob/master/examples/memory_test.rs) to try to replicate your issue. When running on gpu mode, my gpu memory stays constant a bit below 500MB. This is large but I think caused by pytorch internal caching, anyway I don't see the memory increasing.

As per your other questions:
- The way to feed datasets depend a lot on how your dataset are structured. Reading files and then using `of_slice` should be reasonable. There are some helper functions in the `vision` module to help with image datasets.
- Deallocation should be automatic when reaching the scope end (which is one of rust big advantage).
- The memory consumption of `forward_t` depends a lot of what the model is doing. It can certainly double memory consumption and even more.

**Comment by jerry73204** [comment]
It turns out the overly large pre-fetch buffer exhausted the main memory. It's not tch's fault.
Besides, I find Torch forum suggests `no_grad()` to disable gradient engine. It helps reducing memory footprint.

**Comment by LaurentMazare** [comment]
Glad that you were able to track the issue down.
There are two ways to use `no_grad` with the rust bindings, either using `no_grad` with a closure:
```rust
    tch::no_grad(|| {
        // gradients are not tracked here
    });
```
Or using a `no_grad_guard`, in this cases gradient are not tracked until the guard reaches the end of its scope and is dropped.
```rust
{
    let guard = tch::no_grad_guard();
    // gradients are not tracked here
}
```

**Comment by jerry73204** [comment]
Thanks for your reply. The thread can be closed.
