### ISSUE TITLE
Safety of {int64,double}_value

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#46]
The Tensor methods [double_value()](https://docs.rs/tch/0.0.9/tch/struct.Tensor.html#method.double_value) and [int64_value()](https://docs.rs/tch/0.0.9/tch/struct.Tensor.html#method.int64_value) can possibly segfault if idx parameter is nonsense. For example:

```rust
let t: Tensor = (0.0).into(); // t is a scalar tensor
t.double_value(&[0]); // segfault!
```

The code segfaults due to irrelevant dimension index. The idx should be checked beforehand, or `double_value()` should be marked unsafe. It would help that we can identify errors by message rather than helpless segfaults.

**Comment by LaurentMazare** [comment]
Interestingly, this doesn't result in a segfault for me but in the expected panic (about applying select to a  0 dimension tensor).
Not sure what caused this difference of behavior, maybe there are some compile flags that turn on some boundary checks that I have enabled.
Anyway I added a test to check this, it's likely to segfault on your box, but I'll also push some changes so that the dimension are double checked and we exit with a panic in this case rather than segfaulting.
