### ISSUE TITLE
Variable re-using on VarStore

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#48]
It's mostly about my thoughts on `VarStore`.

First it's about the way current impl handles duplicated names. As you see this line, it puts a `HashMap` size suffix when collision. However, it leads to inconsistent namings depending the order you add the tensors.

Suppose we want to add three tensors named _foo_, and other three named _bar_.
If we start from _foo_ tensors and then _bar_, it results in
```
foo, foo__1, foo__2, boo, boo__4, boo__5
```
If we add _bar_ tensors first instead, we have 
```
bar, bar__1, bar__2, foo, foo__4, foo__5
```
I'm not sure it's expected or not. It's fine in most cases. I observed this when I wrote tensor logging. Imagine you're developing a model and change the order of model building functions. It could break the log reader. We can take TensorFlow's naming as reference. At least, we can make it order independent.

Another scenario is variable reusing. The current impl always append a new tensor whenever you call methods on Path. Also, I see no way to obtain saved tensors from `VarStore`. That's inconvenient if we want to build two models on shared variables. We may provide an additional "try_reuse" parameter for this.

**Comment by LaurentMazare** [comment]
Thanks for the feedback.
The naming behaviour is indeed on purpose. As you noted it would not work if you change the order in which tensors are created, however even when using an index per base name the same issue would arise if you change the order in which tensors with the same name are created. The idea there is that you should name tensor uniquely for most use cases (except very simple snippets hence this behavior).
Reusing the same tensors would also be problematic if queried with different sizes or initialization or even with the same random initialization as it's unclear whether you should reinitialize or not.

Re variable reuse, the idea there is that you should reuse things explicitly - rather than relying on some context magic as would be the case with tensorflow. If you want to use a variable twice, you should just create it once with for example `let var = path.zeros(...)` and then pass the `var` tensor to all the places where it is going to be used.
I just added a `get` function so that you can get tensors back based on a path and a name, but I think the clean way to do things is more to pass tensors as described previously.

**Comment by jerry73204** [comment]
I agree reusing should be explicitly specified by users. I think passing variables around would lose the convenience of name space hierarchy. Suppose you build two models partially share some params. While you might keep track of bunch of shared variables, `VarStore` would be a good delegation for this case.

I pushed my entry API `nn::Path` and you can take a look. It's aimed for those who want to check name existence beforehand. I'm not sure if this change is crucial for most users, and we can merge after we have plenty discussions.

**Comment by LaurentMazare** [comment]
Thanks I actually just merged your PR as I think it's a nice addition (as user may indeed end up recoding this kind of thing on their side anyway if they really want to go this way).

**Comment by LaurentMazare** [comment]
Closing now as the PR #49 has been merged and released. Feel free to re-open or create new issues/PRs if you have more thoughts on how to improve usability for this.
