### ISSUE TITLE
Addition of VarStore merging capabilities

### ISSUE THREAD

**Issue by guillaume-be** [LaurentMazare/tch-rs#494]
Hello,

As per https://github.com/guillaume-be/rust-bert/issues/258, I am unsure if it is currently possible to load multiple pre-trained models into a given `VarStore`. A possibility would be for the user to add unique prefixes for each of the models pretrained weights and then use consecutive `load_partial` calls. This has the drawback of losing the validation or the weights names performed during a standard `load` in a `VarStore`.

I have created a draft implementation allowing to take multiple `VarStore` and merging them into a single one for further training by passing them to an optimizer. This allows the following:

```rust
let vs_1 = VarStore::new(Device::Cpu);
let _ = vs_1.root().entry("key_1").or_zeros(&[3, 1, 4]);
let _ = vs_1.root().entry("key_2").or_zeros(&[1, 5, 9]);

let vs_2 = VarStore::new(Device::Cpu);
let _ = vs_2.root().entry("key_3").or_zeros(&[2, 4, 4]);
let _ = vs_2.root().entry("key_4").or_zeros(&[5, 2, 3]);

let merged_vs = VarStore::from_existing(vec![vs_1, vs_2]);
```

The method would look as follows: https://github.com/LaurentMazare/tch-rs/compare/main...guillaume-be:master

If you are supportive of the idea I'd be happy to open a PR to bring these changes to the main branch. Please let me know if there would be another preferred way to load multiple models into a single `VarStore` for combine optimization.

Thank you!

**Comment by LaurentMazare** [comment]
Hi,
This sounds reasonable to me, I indeed don't think that there is a very good way to do this at the moment.
If the main goal is passing all weights to an optimizer, an alternative could be to tweak the optimizer side to allow for this, but maybe there is also some upside in being able to store all the combined variables in a single file in the end.
Some nitpicking:
- Re naming, maybe `merge` or `combine` instead of `from_existing`?
- Instead of taking a slice that must have the same length as the var-store vec, it might be better to take a `Vec<(VarStore, Option<&str>)>` or something like this?

**Comment by lumost** [comment]
> If the main goal is passing all weights to an optimizer, an alternative could be to tweak the optimizer side to allow for this, but maybe **there is also some upside in being able to store all the combined variables in a single file in the end.**

This would indeed be beneficial.  The use case that prompted this was related to combining two pre-trained models into a new model, training on a specific task, and then ideally writing the new model out.  If the new model could be written and loaded as a single artifact , it would provide a nice ease of use win.
