### ISSUE TITLE
Padding mode parameters

### ISSUE THREAD

**Issue by aegroto** [LaurentMazare/tch-rs#532]
Hello, sorry if this question may sound stupid, but I'd need to change the padding mode of convolutional layers or, as an alternative, pad tensors with a different padding mode than zero. Is there any way to do so using this library?

I have read some older issues that argued about the fact that most PyTorch optional parameters are missing because it's difficult to emulate them in Rust, but is there any workaround about it?

**Comment by LaurentMazare** [comment]
Hey,
You're right that there is no easy way to change the padding mode to be other than `zeros` at the moment. This is mostly because it's not exposed directly on the conv operations on the PyTorch C++ side. Instead the Python side applies the appropriate `pad` call [here](https://github.com/pytorch/pytorch/blob/ae67099e88970b8fab140717d8251d9f5e9943b0/torch/nn/modules/conv.py#L456). The pad function is exposed in tch [here](https://github.com/LaurentMazare/tch-rs/blob/c00e2bdc267cab9368852c3da10ad19ecac87dc1/src/wrappers/tensor_generated.rs#L10248) and `mode` should accept other padding modes so you can do the padding operation manually. I'll have a look at adding this by adding a variant to pick the padding mode on the `Conv` layer.
