### ISSUE TITLE
Tensor pretty printing

### ISSUE THREAD

**Issue by LaurentMazare** [LaurentMazare/tch-rs#552]
Calling `tensor.print()` prints the whole tensor so is not convenient most of the time. It would be nicer to have some pretty printing similar to what the python api provides, i.e. using `...` for large tensors.

**Comment by iExalt** [comment]
Speaking of `tensor.print()` Pytorch has `torch.set_printoptions()` to control the precision of printed tensors. It would also be nice if tch-rs could add support for that because I ended up having to `f64::from(tensor.get())` every member of a tensor in order to see them with full precision while debugging.
