### ISSUE TITLE
Panic when displaying Device::Mps tensors

### ISSUE THREAD

**Issue by iExalt** [LaurentMazare/tch-rs#569]
Minimal reproducible example: 
```
fn main() {
    let a = Tensor::ones(&[1], (Kind::Float, Device::Mps));
    dbg!(a);
}
// a = thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Torch("Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

---

https://github.com/LaurentMazare/tch-rs/blob/56681834b0623787cc6df575b4f66f8fee3df6a4/src/tensor/display.rs#L67 

Trying to get a Vec<f64> from a Tensor calls `tensor.to_kind(T::Kind)`, however, Mps tensors cannot be cast to float64.

**Comment by LaurentMazare** [comment]
Thanks for reporting this and digging into it, I've just pushed some changes so that the tensor is moved to the cpu *before* the conversion rather than after. I guess the conversion to `float64` will work well on the cpu though I don't have a mac at hand to check this, let me know if this is still an issue after the change.

**Comment by iExalt** [comment]
Works now! 👍
