### ISSUE TITLE
0.11.0 is not available on cargo.io

### ISSUE THREAD

**Issue by tmvkrpxl0** [LaurentMazare/tch-rs#654]
Despite specifying that libtorch 2.0 is required on README, tch-rs v0.11.0, version that added libtorch 2.0 support afaik, is not available on crate.io. is it intentional?

**Comment by LaurentMazare** [comment]
Yes it's intentional, the github PR was only merged yesterday and I'm doing more tests at the moment, if all goes well the crate.io version will be updated at the end of today/early tomorrow. In the meantime, you can use it (and report any issues!) by specifying the github repo in your cargo dependencies.

**Comment by LaurentMazare** [comment]
The testing went well, this should be available on crates.io now!
