### ISSUE TITLE
InPlace = true in a sequence

### ISSUE THREAD

**Issue by bokenator** [LaurentMazare/tch-rs#709]
Are there any examples on how to replicate `inplace=True` in pytorch?

I do see functions with a underscore suffix such as `relu_()`, but I can't figure out how to use it in a sequence.

Thanks!

**Comment by LaurentMazare** [comment]
Not sure what you mean by using this in a sequence, you should be able to do something like `xs.relu_().sigmoid_()` and this would indeed modify the `xs` tensor in place but maybe you have something else in mind?

**Comment by bokenator** [comment]
My apologies, let me clarify. 

Yes, if `xs` is defined as `mut`, there is no problem using the in-place version of the functions. However, in a Sequence, the `add_fn` passes a closure that only has an immutable reference to `xs`, so we can only use the non-in-place version like `add_fn(|xs| xs.relu())`. Is there something we can do to use the in-place version in a Sequence?

**Comment by LaurentMazare** [comment]
Ah indeed, I agree that it's far from ideal, it's a bit baked in the `Module` trait and would be messy to duplicate or change especially as there is already some duplication because of `ModuleT` (the variant which a "training" flag).
I'm not entirely sure what would be the best here so it would be good to think about this a bit more in depth.
Meanwhile, you can probalby use some "interior mutability" like trick at the moment via `shallow_clone`, I've added a small test to illustrate this [here](https://github.com/LaurentMazare/tch-rs/blob/89f42e05b5c8f6a96e5f0448b21bc01fcac73ecd/tests/nn_tests.rs#L407).

**Comment by bokenator** [comment]
that works very well for now. thanks!
