### ISSUE TITLE
LSTM unbatched?

### ISSUE THREAD

**Issue by Sabn0** [LaurentMazare/tch-rs#719]
Hi,
Reading pytorch documentation, LSTM's inputs can be either batched (i.e, [batch_size, seq_length, n_features]) or unbatched , [seq_length, n_features] .
However, I can see that in this crate the input most be batched. Am I missing something?

Thanks

**Comment by LaurentMazare** [comment]
That sounds right, you may just want to unsqueeze the first dimension on your input to get around this if that's an issue for you.

**Comment by Sabn0** [comment]
Thank you

**Comment by nathanfranke** [comment]
From https://discuss.pytorch.org/t/what-is-seq-len-in-documentation/89337

>seq_len is indeed the length of the sequence such as the number of words in a sentence or the number of characters in a string.
>
>input_size reflects the number of features. Again, in terms of sequences being words in a sentence, this would be the size of the word vectors (e.g, 300). Whatever the number of features is, that will be your input_size.
>
>I full example: Let’s say your batch has 32 sentences of the same length of 50 words (e.g., with padding to ensure equal lengths), and you use word vectors (e.g. word2vec or GloVe) of size 300. then you get
>
>    batch_size = 32
>    seq_len = 50
>    input_size = 300
>
>By default, RNNs in PyTorch expect as input shape (seq_len, batch_size, input_size). But if you define an RNN with batch_first=True, the expected input shape is (batch_size, seq_len, input_size). It’s really just a matter of preference and convenience.

Since `step` takes [batch_size, features], doesn't this mean only sentences of one word would be supported by `step`?  This heavily goes against my intuition. And since `step` for LSTM and GRU calls unsqueeze(1) without checking batch_first, you could probably achieve the expected (IMO) behavior by setting batch_first to false in `RNNConfig`.
