### ISSUE TITLE
tch fails to compile in the presence of PyO3

### ISSUE THREAD

**Issue by diptanu** [LaurentMazare/tch-rs#729]
Hi @LaurentMazare have you seen anyone use tch with PyO3. I am building https://github.com/diptanu/indexify and using tch with rust-bert to run some huggingface transformer pipelines. Naturally, not all models are readily available in Rust, so I am using PyO3 to bring in some python dependencies for models which are not available. 

However, tch is failing to link libtorch while compiling when PyO3 is added as a dependency. In the absence of PyO3 the binary is built without any issues. 

Here is part of the stack trace -
```
   warning: `indexify` (lib) generated 7 warnings
   error: linking with `cc` failed: exit status: 1
     |
     = note: "cc" "-m64" "/tmp/rustcJhnAVi/symbols.o" "/home/diptanuc/Projects/indexify/target/debug/deps/indexify-15e165cff9bd3048.14wlvzqavayxl80f.rcgu.o" "/home/diptanuc/Projects/indexify/target/debug/deps/indexify-15e165cff9bd3048.18wb4faep18xt9lx.rcgu.o" "/home/diptanuc/Projects/indexify/target/debug/deps/indexify-15e165cff9bd3048.1aui2inlwnkujm30.rcgu.o" "/home/diptanuc/Projects/indexify/target/debug/deps/indexify-
     = note: /usr/bin/ld: /home/diptanuc/Projects/indexify/target/debug/deps/libtorch_sys-3cac1932230d9071.rlib(torch_api.o): in function `c10::Device::validate()':
             /home/diptanuc/Src/libtorch/include/c10/core/Device.h:166: undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' 

     = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
     = note: use the `-l` flag to specify native libraries to link
     = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)


```

My code is here - https://github.com/diptanu/indexify/blob/dpr-ve/Cargo.toml

Any ideas or suggestions?

**Comment by diptanu** [comment]
@LaurentMazare Here is a reproduction of the issue in a small app - https://github.com/diptanu/pyo3-tch

**Comment by diptanu** [comment]
Ok another piece of information, looks like PyO3 passes this - -L native=/usr/lib/x86_64-linux-gnu to rustc, if I surgically remove this everything works.

**Comment by LaurentMazare** [comment]
I'm not sure what is going on here but note that compiling your `pyo3-tch` worked out of the box for me using `cargo run`. I tried the various ways to discover libtorch, download/setting LIBTORCH/setting LIBTORCH_USE_PYTORCH and all worked well. Two minor points but I don't think it's related to your issue.
- I would recommend not using the download-libtorch feature by default, this is likely to be deprecated at some point.
- If you want to avoid specifying `LD_LIBRARY_PATH`, you can try copying the `build.rs` file from [here](https://github.com/LaurentMazare/diffusers-rs/blob/main/build.rs), this would set the rpath properly when linking your binary.

Finally the set up is a bit different but [tch-ext](https://github.com/LaurentMazare/tch-ext) is an example of python extension using tch via pyo3 - it works well though as far as I understand it's not what you're aiming to do here as you want to use python from within rust rather than the other way around.

**Comment by diptanu** [comment]
@LaurentMazare Interesting, which distro and OS version, compiler versions are you using?

**Comment by LaurentMazare** [comment]
```bash
➜  ~ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.38
➜  ~ gcc --version  
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
➜  ~ rustc --version
rustc 1.69.0 (84c898d65 2023-04-16)
➜  ~ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

```
Also looking at the [CI on your DPR PR](https://github.com/diptanu/indexify/actions/runs/5105166418/jobs/9176572029?pr=11), it seems that linking/compiling worked fine there too (but then the tests failed)?

**Comment by diptanu** [comment]
Thanks for taking a look! Indeed, it is compiling on the CI. The test failure is related to not checking in the Python Dense Passage Retrieval pipeline, which was my mistake. I will look at this and get back to you soon and update this ticket.

**Comment by diptanu** [comment]
So I am unsure why the build is so messed up in my local machine. But inside a container, it builds and runs just fine. The only difference between your environment and mine is the compiler version, I am on 11.3.0 gcc/cc/c++ 

Closing this issue since this is clearly an environment problem.
