### ISSUE TITLE
Issue Building v0.7 for OpenCV example

### ISSUE THREAD

**Issue by Nic-Gould** [LaurentMazare/tch-rs#745]
Hi there,
[This](https://github.com/metobom/tchrs-opencv-webcam-inference) example requires tch 0.7, but tch 0.7 wont build and gives [these](https://pastebin.com/NZhx6K9f) hefty errors. Is it possible it doesn't build against the current libtorch? 

Using the current version of tch gives [these](https://pastebin.com/NgqmdKqE) much more satisfying errors.
I believe 'of_size_data' can be easily replaced with 'from_data_size'?

Unfortunately I couldn't really follow the documentation for argmax and max to figure out a workaround. Anyone got any hints?

**Comment by LaurentMazare** [comment]
Right, if you look at the [crates.io page for v0.7](https://crates.io/crates/tch/0.7.0), this uses libtorch 1.11.0 which likely explain the compilation error you initially got.
Porting to the latest version of tch is certainly a good idea, you can look at the changelog file to see some of the changes that happened since then, e.g. `from_data_size`. For `argmax` my guess is that you want to use `try_from` rather than `from` (or call something like `double_value`), you can grep through the examples and tests to find some sample code doing this. Let me know if you run into further issues.

**Comment by Nic-Gould** [comment]
You guess right :-)
