### ISSUE TITLE
tch-rs example mnist works fine, but fails to find libtorch_cuda.so as a dependency?

### ISSUE THREAD

**Issue by rustrust** [LaurentMazare/tch-rs#767]
when doing a fully clean build of myproject, i am getting this error:
```
target/release/myproject : error while loading shared libraries: libtorch_cuda.so: cannot open shared object file: No such file or directory
```
but i can build and run the tch-rs mnist example just fine in the same environment.

tch-rs is added to my dependencies via:
```
"tch" = { git = "https://github.com/LaurentMazare/tch-rs" }
```

**Comment by emchristiansen** [comment]
Are you certain your env vars are configured correctly?

These are mine:

```bash
export LIBTORCH_USE_PYTORCH=1
export LIBTORCH_BYPASS_VERSION_CHECK=1
export LD_LIBRARY_PATH=/home/ubuntu/anaconda3/lib/python3.10/site-packages/torch/lib/:$LD_LIBRARY_PATH
```

**Comment by LaurentMazare** [comment]
Indeed you probably want to set your `LD_LIBRARY_PATH` appropriately, you could also try having the same build script as used in the main crate [build.rs](https://github.com/LaurentMazare/tch-rs/blob/8a39c692c961ce17aee4ca46f6b9912c8fa51c70/build.rs#L1): this should set the proper `rpath` value so that there is no need for `LD_LIBRARY_PATH` to be set.

**Comment by rustrust** [comment]
my `LD_LIBRARY_PATH` was missing the trailing `/lib` (i.e. it was `/usr/local/libtorch` rather than `/usr/local/libtorch/lib`). the fact that the mnist example still compiled and ran threw me off! thanks folks.
