### ISSUE TITLE
Save calibrated model to Torch script

### ISSUE THREAD

**Issue by vegapit** [LaurentMazare/tch-rs#93]
Hello there,

Quick question: I was wondering if it was at all possible to save a calibrated model to Torch script? I can see a `load` function but I can not see the `save` counterpart?

Cheers

**Comment by LaurentMazare** [comment]
Indeed currently you can load a jit model but not save one. You can still save the weights in a format that is actually compatible with the c++ frontend but it won't save the network architecture. I haven't looked at how to do this but I suspect this is non-trivial (and to me the typical use case is more train in python and deploy in rust rather than the other way around but still it may be an interesting thing to support).

**Comment by vegapit** [comment]
For neural networks, I would argue that it makes sense to use Rust for modelling and training purposes, simply because computing performance makes a big difference at this stage and not at use time. The simple use case for a JIT export is to be able to use the model in an existing (non-Rust) web service without having to set up a dedicated API or using Web Assembly (not even sure it could work). I agree that if the dedicated C function does not exist in the Torch library, it is most likely non trivial and probably not worth losing some sleep over.

**Comment by LaurentMazare** [comment]
Closing for now as this is likely to be some substantial work and I don't think anyone plans on looking at it (happy to get a PR for it though).
